config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'dashboard#index'

  resources :pledgegroups

  get 'session', to: 'session#login'
  get 'session/create', to: 'session#create'
  get 'session/sign_out', to: 'session#sign_out'

  root to: 'session#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pledgegroup.rb
class Pledgegroup < ApplicationRecord
    serialize :admins, Array
    serialize :pledges, Array

    validates :budget, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :verify_login

  def current_user
    @user ||= User.find_by(user_id: session[:user_id])
  end

  private
  def verify_login
    if current_user.nil?
      redirect_to session_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/pledgegroups_controller.rb
class PledgegroupsController < ApplicationController
  def index
    @pledgegroups = Pledgegroup.all
  end

  def new
    @pledgegroup = Pledgegroup.new
  end

  def create
    @pledgegroup = Pledgegroup.new({ budget: params[:pledgegroup][:budget], admins: [current_user], is_public: (params[:is_public] ? true : false)})

    if @pledgegroup.save
      redirect_to pledgegroups_url
    else
      flash[:error] = "Pledge group could not be saved with the given input"
      redirect_back fallback_location: new_pledgegroup_path
    end
  end



  def edit
    @pledgegroup = Pledgegroup.find(params[:id])
  end

  def update
    @pledgegroup = Pledgegroup.find(params[:id])

    if @pledgegroup.update({ budget: params[:pledgegroup][:budget], admins: [current_user], is_public: (params[:is_public] ? true : false)})
      redirect_to pledgegroups_url
    else
      flash[:error] = "Pledge group could not be saved with the given input"
      redirect_back fallback_location: edit_pledgegroup_path
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :verify_login

  def login
    if current_user
      redirect_to dashboard_path
    end
  end

  def create
    if id_token = flash[:google_sign_in]['id_token']
      user_params = GoogleSignIn::Identity.new(id_token)
      if (!User.exists?(user_id: user_params.user_id))
        new_user = User.new
        new_user.user_id = user_params.user_id
        new_user.name = user_params.name
        new_user.email = user_params.email_address
        new_user.profile_img = user_params.avatar_url
        new_user.save!
      end

      session[:user_id] = user_params.user_id
      redirect_to dashboard_path
    else
      redirect_to session_path, alert: 'Login failed'
    end
  end

  def sign_out
    session.delete(:user_id)
    redirect_to session_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pledge2Gether</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>

    <%= favicon_link_tag '/pledge2gether_logo.png' %>
  </head>

  <body>
    <% if controller_name != "session" %>
      <div class="row navbar-fixed">
        <div class="left brand-logo">
          <%= link_to root_url do %>
            <%= image_tag("/pledge2gether_logo.png", class: "brand-logo__image") %>
            Pledge2Gether
          <% end %>
        </div>
        <div class="right profile dropdown-trigger" data-target='profile__options'>
          <%= image_tag(@user.profile_img , :class => "left circle profile__img") %>
          <div class="right profile_info">
            <span class="profile__name"><%= @user.name %> </span>
            <br>
            <span class="profile__email"><%= @user.email %> </span>
          </div>
        </div>
          <ul id='profile__options' class='dropdown-content'>
            <li class="dropdown__link">
              <%= link_to session_sign_out_path do%>
                <%= icon("fas", "sign-out-alt") %> Sign Out
              <% end %>  
            </li>
          </ul>
      </div>
      <div class="sidebar">
        <div class="row">
          <ul>
            <li class="sidebar__link">
              <%= link_to dashboard_path do %>
                <%= icon("fas", "check-square") %> Dashboard
              <% end %>
            </li>
            <li class="sidebar__link">
              <%= link_to pledgegroups_path do %>
                <%= icon("fas", "list") %> Pledge Groups
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <div class="main_content">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>

  </body>
</html>

app/views/pledgegroups/_form.html.erb
<%= form_with model: @pledgegroup do |form| %>
    <p>
        <label>
            <input type="checkbox" class="filled-in" name="is_public" id="is_public" value="true"/>
            <span>Public</span>
        </label>
    </p>

    <div>
        <%= form.label :budget %><br>
        <%= form.text_field :budget %>
        <% @pledgegroup.errors.full_messages_for(:budget).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/pledgegroups/edit.html.erb
<div class="edit-pledge-group">
    <h1>Edit Article</h1>
    <%= render "form", pledgegroup: @pledgegroup %>
</div>

app/views/pledgegroups/index.html.erb
<div class="pledge-groups-container">
    <h3>Pledge Groups</h3>

    <%= button_to "New Pledge Group", new_pledgegroup_path, :method => "get" %>

    <div class="pledge-group-list">  
     <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>admins</th>
                <th>public</th>
                <th>budget</th>
                <th>amount paid</th>
            </tr>
        </thead>

        <tbody>
            <% @pledgegroups.each do |pledgegroup| %>
            <tr>
                <td><%= pledgegroup.id %></td>
                
                <td>
                    <%= pledgegroup.admins.each do |user| %>
                        <p><%= user.name %></p>
                    <% end %>
                </td>
                <td><%= pledgegroup.is_public %></td>
                <td><%= pledgegroup.budget %></td>
                <td><%= pledgegroup.amount_paid %></td>
                <td><%= link_to "edit", edit_pledgegroup_path(pledgegroup), :method => "get" %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/pledgegroups/new.html.erb
<div class="new-pledge-group">
  <h3>New Pledge Group</h3>
  <%= render "form", pledgegroup: @pledgegroup %>
</div>

app/views/session/login.html.erb
<div class="login-background">
  <div class="login__container center">
    <%= image_tag("/login_header.png", class: "login__container-header") %>

    <div class="login__container-contents">
      <% if flash[:alert] %>
        <div class="alert"><%= flash[:alert] %></div>
      <% end %>

      <h4>🎉 Welcome to Maxtime! 🎉</h4>
      <h5><i>Log in to start streamlining your life!</i> ⏱</h5>
      <br>
      <br>
      <%= google_sign_in_button proceed_to: session_create_path, class: "btn-large red" do %>
        <div class="left google__logo"> <%= icon("fab", "google") %> </div>
        <div class="right google__text"> Sign in with Google </div>
      <% end %>

    </div>

  </div>
</div>